### ISSUE TITLE
dont work with python 3.12?

### ISSUE THREAD

**Issue by popedead** [Easymode-ai/ComfyUI-BPT#4]
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  dont work with python 3.12?
